name: Streamlit CI-CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  streamlit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Smoke Test Streamlit
        run: |
          nohup streamlit run app/home_app.py & 
          sleep 10
          curl --fail http://localhost:8501/_stcore/health